name: tangram-env
dependencies:
  - python=3.8
  - pip>=21
  - pytorch=1.10
  - scipy=1.7
  - matplotlib=3.4
  - seaborn=0.11
  - jupyterlab
  - pip:
      - numpy>=1.19,<1.24
      - pandas>=1.2
      - scanpy>=1.6
      - scikit-learn
      - tqdm
