name: Tangram QA

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with: 
          auto-activate-base: true 
          activate-environment: ""

      - name: create environment which is aligned with production environment plus pytest
        run: |
          conda env update --file environment.yml --name base
          pip install pytest

      - name: run test
        run: |
          conda init bash
          exec bash
          conda activate base
          conda info
          conda list
          pytest tests/
        